### ISSUE TITLE
Flash games and sky snake still not working but boggle randomly fixed itself.

### ISSUE THREAD

**Issue by ghost** [stb-gaming/sky#18]
as per above.

**Comment by tumble1999** [comment]
Wrong repo, this repo is about the high scores website.
The current repo is stb-gaming/sky

**Comment by ghost** [comment]
> Wrong repo, this repo is about the high scores website. The current repo is stb-gaming/sky

there ive transfered over the issue

**Comment by ghost** [comment]
update: for now ive changed the broken games name on high scores to say the games name then broken in brackets like this.
example: sky games (broken)

**Comment by JohnPykett1999** [comment]
after changing some files it broken again

**Comment by JohnPykett1999** [comment]
update: ive restored 4 flash games by using an alternative link

**Comment by ghost** [comment]
update 2: so ive changed the broken games file with an alternative url
